import { Platform, StyleSheet } from "react-native";
import { Colors } from "../../../styles/colors";

export const defalutSearchDropdownStyle = StyleSheet.create({
  container: {
    display: "flex",
    zIndex: 22,
    width: "100%",
    flexDirection: "column",
    fontFamily: "Inter-Regular",
    gap: 4,
  },
  label: {
    fontSize: 14,
    fontFamily: "Inter-Regular",
    color: Colors.black_01,
    alignItems: "center",
  },
  chipsContainer: {
    flexDirection: "row",
    flexWrap: "wrap", // Allow items to wrap to the next line
    gap: 5,
    height: 30,
  },

  chips: {
    height: 30,
    borderWidth: 1 / 2,
    borderColor: "black",
    borderRadius: 8,
    padding: 4,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  image: {
    height: 20,
    width: 20,
    borderRadius: 20,
  },
  dropdownValueContainer: {
    position: "relative",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 5,
    borderColor: Colors.black_04,
    borderWidth: 1 / 2,
    shadowColor: Colors.shadow_color,
    elevation: 2,
    shadowOffset: { width: 3, height: 3 },
    backgroundColor: Colors.white,
  },
  dropdownListontainer: {
    width: "100%",
    position: "absolute",
    top: 50,
    zIndex: 50,
    borderRadius: 5,
    borderColor: Colors.black_04,
    borderWidth: 1 / 2,
    shadowColor: Colors.shadow_color,
    elevation: 2,
    shadowOffset: { width: 3, height: 3 },
    backgroundColor: Colors.white,
  },
  dropdownItem: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomColor: Colors.gray_07,
    borderBottomWidth: 1,
  },
  dropdownItemImageSection: {
    zIndex: 12,
    gap: 5,
    paddingHorizontal: 14,
    paddingVertical: 10,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    borderBottomColor: Colors.gray_07,
  },
  inputFieldContainer: {
    width: "100%",
    fontSize: 14,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 5,
    borderWidth: 1 / 2,
    borderColor: Colors.black_04,
    backgroundColor: Colors.white,
    paddingVertical: 8,
    paddingLeft: 14, // Adjust this value to create space between the left edge and the CrossIcon
  },
  inputField: {
    flex: 1, // Take up remaining width
    color: Colors.gray_06,
    ...(Platform.OS === "web" ? { outlineStyle: "none" } : {}),
  },
  dropdownLabel: {
    fontSize: 14,
  },
  dropdownLabelWithShadow: {
    // elevation: 8,
    shadowColor: Colors.black_03,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
  },
});
